version: '3.9'

services:
  nginx:
    image: docker.io/library/nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: always

  rosblox-studio:
    image: ghcr.io/rosblox/studio:latest
    volumes:
      - ./studio/layout.json:/src/layout.json
      - ./studio/layout.json:/foxglove/default-layout.json
    ports:
      - 8080:8080
    restart: always

  ros-rosbridge-suite:
    image: ghcr.io/rosblox/ros-rosbridge-suite:humble
    ports:
      - 9090:9090
    restart: always
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  ros-rslidar-sdk:
    image: ghcr.io/rosblox/ros-rslidar-sdk:humble 
    restart: always
    network_mode: "host"
    privileged: true
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
    command: su - ros /run.sh
